# .terraform-docs.yml
formatter: markdown table
header-from: main.tf
sort:
  enabled: true
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
recursive:
  enabled: true
  path: modules
  include-main: false